project_id = "cuoqjgahpfymxqrdlzlf"

[functions.create-merchant]
verify_jwt = false

[functions.delete-merchant]
verify_jwt = false

[functions.send-sms-otp]
verify_jwt = false

[functions.verify-sms-otp]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.calculate-order-eta]
verify_jwt = true

[functions.calculate-waitlist-eta]
verify_jwt = true

[functions.get-venue-analytics]
verify_jwt = true

[functions.get-platform-patron-data]
verify_jwt = true