project_id = "cuoqjgahpfymxqrdlzlf"

[functions.create-merchant]
verify_jwt = false

[functions.send-sms-otp]
verify_jwt = false

[functions.verify-sms-otp]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false